version: '3'

networks:
  default:
    driver: bridge

services:
  db:
    image: mysql:5.7
    container_name: db
    command: --innodb-use-native-aio=0
    restart: always
    tty: true
    volumes:
      - ./db/volume:/var/lib/mysql
      - ./db/ddl:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=appdb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - default

  app:
    build:
      context: ./app
    container_name: app
    image: joaoalmeida200/nginx-challenge-app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    command: node index.js
    restart: always
    volumes:
      - ./app:/usr/src/app
    networks:
      - default
    expose:
      - 3000
    depends_on:
      - db

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    image: joaoalmeida200/nginx-challenge-proxy
    restart: always
    networks:
      - default
    ports:
      - "8080:80"
    depends_on:
      - app
